version: "3.9"

include:
  - path: compose-helpers/compose.base.dev.yml

services:
  #
  #
  #
  ################################################################################
  # whoami
  ################################################################################
  whoami:
    container_name: whoami
    image: traefik/whoami
    networks:
      - proxy
    labels:
      - "traefik.enable=true" # enable traefik for this container
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)" # set the domain rule
